# ==============================================================================
# UXPLIMA Skyblock Operational Gameplay Settings & Toggles (Section 2.41)
# ==============================================================================

quality-of-life {
    obsidian-to-lava = true
    void-teleport {
        members = true
        visitors = true
    }
    default-command-action = "auto"
    island-names {
        enabled = true
        min-length = 3
        max-length = 16
    }
    teleport-warmup-seconds = 3
}

combat-protection {
    teleport-on-pvp-enable = true
    immune-to-pvp-when-teleport = true
    pvp-teleport-invulnerability-seconds = 10
    stop-border-crossing = true
}

performance-optimization {
    disable-redstone-offline = true
    afk-integrations {
        disable-spawning = true
        disable-redstone = true
    }
    nether-roof = false
}

economy-mechanics {
    sync-worth-with-shop = "BUY"
    negative-level-allowed = false
    end-dragon-fight {
        enabled = true
    }
}
