name: uxmSkyblock
version: '${version}'
main: com.uxplima.uxmskyblock.bukkit.bootstrap.UxMSkyblockPlugin
api-version: '26.2'
folia-supported: true
description: Enterprise-grade, distributed, event-driven Skyblock platform
author: UXPLIMA
dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    mcMMO:
      load: BEFORE
      required: false
    floodgate:
      load: BEFORE
      required: false
    Geyser-Spigot:
      load: BEFORE
      required: false
    dynmap:
      load: BEFORE
      required: false
    BlueMap:
      load: BEFORE
      required: false
    Pl3xMap:
      load: BEFORE
      required: false

