name: uxmSkyblock
version: '${version}'
main: com.uxplima.uxmskyblock.bukkit.bootstrap.UxMSkyblockPlugin
api-version: '1.21'
folia-supported: true
description: Enterprise-grade, distributed, event-driven Skyblock platform
author: UXPLIMA
softdepend:
  - Vault
  - PlaceholderAPI

